### ISSUE TITLE
Suggestion to add extrasteps to r-universe

### ISSUE THREAD

**Issue by jrosell** [EmilHvitfeldt/extrasteps#72]
Hi @EmilHvitfeldt. When trying to use extrasteps from some sites it would help to use r-universe instead of github. It's easier than CRAN and it's useful for example in Kaggle.

You may already know how to do it, but for completeness here's how: https://docs.r-universe.dev/publish/set-up.html

Feel free to close this issue if you don't feel like doing it.

**Comment by EmilHvitfeldt** [comment]
Since r-uinverse right now uses automatic tracking of my packages, i don't want to switch to manual.

I have been thinking about sending to CRAN for a while, so i'm gonna do it now :D https://github.com/EmilHvitfeldt/extrasteps/issues/73

**Comment by jrosell** [comment]
Thanks for the update :)
